Gifts/Controllers/ApplicationController.cs
using UCDArch.Web.Controller;
using UCDArch.Web.Attributes;

namespace Gifts.Controllers
{
    [Version(MajorVersion = 3)]
    //[ServiceMessage("Gifts", ViewDataKey = "ServiceMessages", MessageServiceAppSettingsKey = "MessageService")]
    public abstract class ApplicationController : SuperController
    {
    }
}

Gifts/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gifts.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Gifts/Controllers/MockupController.cs
using System.Web;
using System.Web.Mvc;
using UCDArch.Web.ActionResults;

namespace Gifts.Controllers
{
    public class MockupController : Controller
    {
        //
        // GET: /Mockup/
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            return new JsonNetResult(new { success = true });
        }
	}
}

Gifts/Controllers/SampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCDArch.Web.Attributes;

namespace Gifts.Controllers
{
    [HandleError]
    [HandleTransactionsManually]
    public class SampleController : ApplicationController
    {
        public ActionResult Index()
        {
            ViewBag.ErrorMessage = "Houston we have a problem... just kidding, this is only a test";
            Message = "Sample Message from the Controller";
            
            return View();
        }

        public ActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Form(string data)
        {
            Message = "The form was submitted successfully";

            return View();
        }

        public ActionResult Table()
        {
            return View();
        }

        public ActionResult DataTable()
        {
            return View();
        }

        public ActionResult DisplayForm()
        {
            return View();
        }
    }
}

Gifts/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Gifts/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Gifts/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Advancement Services Central Gift Processing Mockup</h1>
    <p class="lead">Samples and mockups for the Gift processing application</p>
    <p><a href="@Url.Action("Index", "Mockup")" class="btn btn-primary btn-large">Check it out &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Gifts/Views/Mockup/_Modals.cshtml
<script type="text/ng-template" id="donorTemplate.html">
    <a>
        <span bind-html-unsafe="match.label | typeaheadHighlight:query"></span>
        <p class="small">{{match.model.address}}</p>
    </a>
</script>

<script type="text/ng-template" id="newDonorTemplate.html">
    <div class="modal-header">
        <h3>Create a new donor</h3>
    </div>
    <div class="modal-body">
        <form>
            <fieldset>
                <legend>
                    The following fields are all required to create a new donor
                </legend>
                <div class="form-group">
                    <span>Donor Name</span>
                    <input type="text" class="form-control" placeholder="donor name" ng-model="newDonor.name" />
                </div>
                <div class="form-group">
                    <span>Address</span>
                    <input type="text" class="form-control" placeholder="1 Shields Ave, Davis, CA, 95616" ng-model="newDonor.address" />
                </div>
                <div class="form-group">
                    <span>Phone</span>
                    <input type="text" class="form-control" placeholder="phone number, ex: (530) 555-5555" ng-model="newDonor.phone" />
                </div>
            </fieldset>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" ng-click="ok()">Create!</button>
        <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
    </div>
</script>
<script type="text/ng-template" id="lookupDonorTemplate.html">
    <div class="modal-header">
        <h3>Lookup existing Advance donor</h3>
    </div>
    <div class="modal-body">
        <form>
            <fieldset>
                <legend>
                    Lookup an existing donor. If you already know the donor's advance ID, close this window and enter it directly.
                </legend>
                <div class="form-group">
                    <span>First Name</span>
                    <input type="text" class="form-control" placeholder="first name" ng-model="searchName.first" />
                </div>
                <div class="form-group">
                    <span>Last Name</span>
                    <input type="text" class="form-control" placeholder="last name" ng-model="searchName.last" />
                </div>
            </fieldset>
            <div>
                <button class="btn btn-primary" ng-click="search()">Search!</button>
            </div>
        </form>
        <h3>Search Results</h3>
        <div>
            <div class="list-group" ng-repeat="donor in foundDonors">
                <a href="#" ng-click="select(donor)" class="list-group-item">
                    <h4><i class="fa fa-male"></i> {{donor.FullName}} ({{donor.Id_Number}})</h4>
                    <p>{{donor.Address}}</p>
                </a>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-warning" ng-click="cancel()">Close</button>
    </div>
</script>
<script type="text/ng-template" id="newAccountTemplate.html">
    <div class="modal-header">
        <h3>Create a new fund</h3>
    </div>
    <div class="modal-body">
        <form>
            <fieldset>
                <legend>
                    The following fields are all required to create a new fund
                </legend>
                <div class="form-group">
                    <span>Agency</span>
                    <select class="form-control" ng-model="newAccount.agency">
                        <option>Regents</option>
                        <option>Foundation</option>
                    </select>
                </div>
                <div class="form-group">
                    <span>KFS (Kuali) Account Number</span>
                    <input type="text" class="form-control" placeholder="KFS Account Number" readonly ng-model="newAccount.id" />
                </div>
                <div class="form-group">
                    <span>KFS (Kuali) Account Name</span>
                    <input type="text" class="form-control" placeholder="KFS Account Name" readonly ng-model="newAccount.name" />
                </div>
                <div class="form-group">
                    <span>UC Account Number</span>
                    <input type="text" class="form-control" placeholder="UC Account Number" ng-model="newAccount.ucaccount" />
                </div>
                <div class="form-group">
                    <span>Fund Name</span>
                    <input type="text" class="form-control" placeholder="Fund Name" ng-model="newAccount.fund" />
                </div>
                <div class="form-group">
                    <span>Program Name</span>
                    <input type="text" class="form-control" placeholder="Program Name" ng-model="newAccount.program" />
                </div>
                <div class="form-group">
                    <span>Purpose</span>
                    <input type="text" class="form-control" placeholder="Purpose" ng-model="newAccount.purpose" />
                </div>
            </fieldset>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" ng-click="ok()">OK</button>
        <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
    </div>
</script>

Gifts/Views/Sample/DataTable.cshtml
@model dynamic

@{
    ViewBag.Title = "Data Tables";
}

@Styles.Render("~/Content/DataTables-1.9.4/media/css/dataTables")

@section subhead
{
    <h1>Data Tables Example</h1>

    <div>
        <p>This is an example of using Data Tables to create interactive client-side tables</p>
    </div>
}

@section subnav
{
    <li>@Html.ActionLink("Sample Index", "Index")</li>
    <li>@Html.ActionLink("Form", "Form")</li>
    <li>@Html.ActionLink("Table", "Table")</li>
    <li class="active">@Html.ActionLink("Data Tables", "DataTable")</li>
    <li>@Html.ActionLink("Display Form", "DisplayForm")</li>
}

@section AdditionalScripts
{
    @Scripts.Render("~/bundles/datatables")

    <script type="text/javascript">
        $(function () {
            $(".table").dataTable({
                "aaSorting": [[1, "asc"]], //Default sort on second column
                "aoColumnDefs": [
                    { 'bSortable': false, 'aTargets': [0, 5] } //Disables sort on icon columns
                ]
            });
        });
    </script>
    
}

<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th></th>
            <th>#</th>
            <th>Name</th>
            <th>Gender</th>			
            <th>Score</th>
            <th></th>		
        </tr>
    </thead>
    <tbody>
        @{ var rand = new Random();}
        @for (int i = 1; i < 50; i++)
        {
            <tr>
                <td>
	    			<a href='#' class="btn btn-default" title="Details"><i class="fa fa-file-o"></i></a>
				    <a href='#' class="btn btn-default" title="Edit"><i class="fa fa-edit"></i></a>
    			</td>
                <td>@i</td>
                <td>Person @i</td>
                <td>@(i % 2 == 0 ? "Male" : "Female")</td>
                <td>@(rand.Next(1000))</td>
			    <td>
				    <a href='#' class="btn btn-danger" title="Remove"><i class="fa fa-times"></i></a>
			    </td>
            </tr>
        }
    </tbody>
</table>

Gifts/Views/Sample/DisplayForm.cshtml
@{
    ViewBag.Title = "Display Form";
}

@section SubNav {
    <li>@Html.ActionLink("Sample Index", "Index")</li>
    <li>@Html.ActionLink("Form", "Form")</li>
    <li>@Html.ActionLink("Table", "Table")</li>
    <li>@Html.ActionLink("Data Tables", "DataTable")</li>
    <li class="active">@Html.ActionLink("Display Form", "DisplayForm")</li>
}

@section subhead
{
    <h1>Display Form Example</h1>

    <div>
        <p>This is an example of a page that displays some object or infomation</p>
    </div>
}

<form class="well well-small">
    <fieldset>
        <legend>Form info</legend>
        <div class="form-group">
            <label>Name</label>
            <div class="form-control-static">Bob Dobalina</div>
        </div>
        <div class="form-group">
            <label>Email</label>
            <div class="form-control-static">bdobalina@gmail.com</div>
        </div>
        <div class="form-group">
            <label>Phone</label>
            <div class="form-control-static">530-555-5231</div>
        </div>
    </fieldset>
</form>

Gifts/Views/Sample/Form.cshtml
@{
    ViewBag.Title = "Form Demo";
}

@section subhead
{
    <h1>Form Example</h1>

    <div>
        <p>This is an example of what a standard form would look like</p>
    </div>
}

@section subnav
{
    <li>@Html.ActionLink("Sample Index", "Index")</li>
    <li class="active">@Html.ActionLink("Form", "Form")</li>
    <li>@Html.ActionLink("Table", "Table")</li>
    <li>@Html.ActionLink("Data Tables", "DataTable")</li>
    <li>@Html.ActionLink("Display Form", "DisplayForm")</li>
}

<form role="form" action="@Url.Action("Form")" method="POST" class="well well-large">
    <fieldset>
        <legend>Personal Information</legend>
        <div class="form-group">
            <label for="inputFirstName" class="required">First Name</label>
            <input type="text" class="form-control" id="inputFirstName" name="inputFirstName" placeholder="First Name" data-val="true" data-val-required="First Name Required">
            <span class="field-validation-valid" data-valmsg-for="inputFirstName" data-valmsg-replace="true"></span>
        </div>        
        <div class="form-group">
            <label for="inputLastName" class="required">Last Name</label>
            <input type="text" class="form-control" id="inputLastName" name="inputLastName" placeholder="Last Name" data-val="true" data-val-required="Last Name Required">
            <span class="field-validation-valid" data-valmsg-for="inputLastName" data-valmsg-replace="true"></span>
        </div>
        <div class="form-group">
            <label for="inputEmail">Email address</label>
            <input type="email" class="form-control" id="inputEmail" name="inputEmail" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="inputBirthday">Birthday</label>
            <input type="date" class="form-control" id="inputBirthday" name="inputBirthday">
        </div>
    </fieldset>
    <fieldset>
        <legend>Contact Information</legend>
        <div class="form-group">
            <label for="inputAddress">Address</label>
            <input type="text" class="form-control" id="inputAddress" name="inputAddress" placeholder="Address"/>
        </div>
        <div class="form-group">
            <label for="inputState">State</label>
            <select id="inputState" class="form-control">
                <option value>-- Select A State --</option>
                <option value="CA">California</option>
                <option value="NY">New York</option>
            </select>
        </div>
    </fieldset>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="button" class="btn btn-link">Cancel</button>
</form>			

Gifts/Views/Sample/Index.cshtml
@{
    ViewBag.Title = "Page Sample Home";
}

@section subhead
{
    <h1>Page Samples</h1>

    <div>
        <p>Check out the links for a sample of different standard pages you might encounter in the wild</p>
    </div>
}

@section subnav
{
    <li class="active">@Html.ActionLink("Sample Index", "Index")</li>
    <li>@Html.ActionLink("Form", "Form")</li>
    <li>@Html.ActionLink("Table", "Table")</li>
    <li>@Html.ActionLink("Data Tables", "DataTable")</li>
    <li>@Html.ActionLink("Display Form", "DisplayForm")</li>
}

Gifts/Views/Sample/Table.cshtml
@{
    ViewBag.Title = "Table Demo";
}

@section subhead
{
    <h1>Table Example</h1>

    <div>
        <p>This is an example of a good looking table without any paging/sorting</p>
    </div>
}

@section subnav
{
    <li>@Html.ActionLink("Sample Index", "Index")</li>
    <li>@Html.ActionLink("Form", "Form")</li>
    <li class="active">@Html.ActionLink("Table", "Table")</li>
    <li>@Html.ActionLink("Data Tables", "DataTable")</li>
    <li>@Html.ActionLink("Display Form", "DisplayForm")</li>
}

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>#</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Social Security</th>
			<th>Gender</th>							
		</tr>
	</thead>
	<tbody>
	    <tr>
	        <th>1</th>
	        <td>Philip</td>
	        <td>Fry</td>
	        <td>123-33-4032</td>
	        <td>Male</td>
	    </tr>
		<tr>
			<td>2</td>
			<td>John</td>
			<td>Zoidberg</td>
			<td>342-23-2423</td>
			<td>Male</td>
		</tr>
		<tr>
			<td>3</td>
			<td>Hermes</td>
			<td>Conrad</td>
			<td>493-23-4323</td>
			<td>Male</td>
		</tr>
		<tr> 
			<td>4</td>
			<td>Amy</td>
			<td>Wong</td>
			<td>454-45-4324</td>
			<td>Female</td>
		</tr>
		<tr>
			<td>5</td>
			<td>Turanga</td>
			<td>Leela</td>
			<td>134-31-3431</td>
			<td>Female</td>
		</tr>
	</tbody>
</table>					

Gifts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Must be at the top of head, loads fonts -->
    @*<script type="text/javascript" src="//use.typekit.net/ykm7bho.js"></script>
    <script type="text/javascript">try { Typekit.load(); } catch (e) { }</script>*@

    <!-- Le styles -->
    @Styles.Render("~/Content/styles")
    
    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="~/favicon.ico">

    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    @Html.Partial("_Navigation")

    <div class="jumbotron">
        <div class="container">
            @RenderSection("subhead", required: false)
            <ul class="nav nav-pills pull-right">
                @RenderSection("SubNav", required: false)
            </ul>
        </div>
    </div>

    <div class="container">
        <header>
            @if (!string.IsNullOrWhiteSpace(ViewBag.ErrorMessage))
            {
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    @ViewBag.ErrorMessage
                </div>
            }
            
            @if (!string.IsNullOrWhiteSpace(TempData["Message"] as string))
            {
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    @TempData["Message"]
                </div>
            }
        </header>
        
        <div class="container">
            @RenderBody()
        </div>


        <hr>
        <footer>
            <p>&copy; College of Agricultural and Environmental Sciences, University of California at Davis</p>
        </footer>
    </div>
    
    @Html.Partial("_ServiceMessages")

    @Scripts.Render("~/bundles/jquery")
@*    @Scripts.Render("~/bundles/jqueryval")*@
  @*  @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("AdditionalScripts", required: false)
    
    <script>
        $(function () {
            //Choose the active link depending on your current controller
            var controller = '@ViewContext.RouteData.Values["controller"].ToString().ToLower()';
            $("#nav-" + controller).addClass("active");
        })
    </script>
</body>
</html>

Gifts/Views/Shared/_LayoutOrig.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Gifts/Views/Shared/_Navigation.cshtml
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img src="@Url.Content("~/Content/images/logo.png")" alt="UC Davis Logo" class="navbar-logo" />
                Gifts Mockup
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="nav-home">@Html.ActionLink("Home", "Index", "Home")</li>
                <li id="nav-home">@Html.ActionLink("Mockups", "Index", "Mockup")</li>
                <li id="nav-sample">@Html.ActionLink("Sample", "Index", "Sample")</li>
                <li id="nav-order">@Html.ActionLink("Order", "Index", "Order")</li>
                <li id="nav-json">@Html.ActionLink("Json", "Index", "Json")</li>
                <li id="nav-about">@Html.ActionLink("About", "About", "Home")</li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Welcome, User Person <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="fa fa-cog"></i> Preferences</a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i> Contact Support</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-off"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!--/.nav-collapse -->
</div>

Gifts/Views/Shared/_ServiceMessages.cshtml
@{
    var messages = ViewData["ServiceMessages"] as UCDArch.Web.Services.ServiceMessage[] ?? new UCDArch.Web.Services.ServiceMessage[0];
    var hasMessages = messages.Any();
}        

@if (hasMessages)
{
    <div id="service-message" class="navbar-fixed-bottom">
        @foreach(var message in messages.OrderByDescending(a => a.Critical).ThenBy(a => a.Global)){
            var importanceIcon = message.Critical ? "fa-exclamation-circle" : "fa-info-circle";
            var messageType = message.Critical ? "critical-message" : "info-message";
            <div class="container">
                <p class="@messageType"><i class="fa @importanceIcon"></i>@message.Message</p>
            </div>
        }
    </div>
}